export type ThaiRegion = "north" | "northeast" | "central" | "east" | "west" | "south";

export type ThaiProvince = {
  slug: string;
  nameTh: string;
  nameEn: string;
  region: ThaiRegion;
};

export const thaiProvinces: ThaiProvince[] = [
  { slug: "bangkok", nameTh: "กรุงเทพมหานคร", nameEn: "Bangkok", region: "central" },
  { slug: "amnat-charoen", nameTh: "อำนาจเจริญ", nameEn: "Amnat Charoen", region: "northeast" },
  { slug: "ang-thong", nameTh: "อ่างทอง", nameEn: "Ang Thong", region: "central" },
  { slug: "bueng-kan", nameTh: "บึงกาฬ", nameEn: "Bueng Kan", region: "northeast" },
  { slug: "buriram", nameTh: "บุรีรัมย์", nameEn: "Buriram", region: "northeast" },
  { slug: "chachoengsao", nameTh: "ฉะเชิงเทรา", nameEn: "Chachoengsao", region: "east" },
  { slug: "chai-nat", nameTh: "ชัยนาท", nameEn: "Chai Nat", region: "central" },
  { slug: "chaiyaphum", nameTh: "ชัยภูมิ", nameEn: "Chaiyaphum", region: "northeast" },
  { slug: "chanthaburi", nameTh: "จันทบุรี", nameEn: "Chanthaburi", region: "east" },
  { slug: "chiang-mai", nameTh: "เชียงใหม่", nameEn: "Chiang Mai", region: "north" },
  { slug: "chiang-rai", nameTh: "เชียงราย", nameEn: "Chiang Rai", region: "north" },
  { slug: "chonburi", nameTh: "ชลบุรี", nameEn: "Chonburi", region: "east" },
  { slug: "chumphon", nameTh: "ชุมพร", nameEn: "Chumphon", region: "south" },
  { slug: "kalasin", nameTh: "กาฬสินธุ์", nameEn: "Kalasin", region: "northeast" },
  { slug: "kamphaeng-phet", nameTh: "กำแพงเพชร", nameEn: "Kamphaeng Phet", region: "north" },
  { slug: "kanchanaburi", nameTh: "กาญจนบุรี", nameEn: "Kanchanaburi", region: "west" },
  { slug: "khon-kaen", nameTh: "ขอนแก่น", nameEn: "Khon Kaen", region: "northeast" },
  { slug: "krabi", nameTh: "กระบี่", nameEn: "Krabi", region: "south" },
  { slug: "lampang", nameTh: "ลำปาง", nameEn: "Lampang", region: "north" },
  { slug: "lamphun", nameTh: "ลำพูน", nameEn: "Lamphun", region: "north" },
  { slug: "loei", nameTh: "เลย", nameEn: "Loei", region: "northeast" },
  { slug: "lopburi", nameTh: "ลพบุรี", nameEn: "Lopburi", region: "central" },
  { slug: "mae-hong-son", nameTh: "แม่ฮ่องสอน", nameEn: "Mae Hong Son", region: "north" },
  { slug: "maha-sarakham", nameTh: "มหาสารคาม", nameEn: "Maha Sarakham", region: "northeast" },
  { slug: "mukdahan", nameTh: "มุกดาหาร", nameEn: "Mukdahan", region: "northeast" },
  { slug: "nakhon-nayok", nameTh: "นครนายก", nameEn: "Nakhon Nayok", region: "central" },
  { slug: "nakhon-pathom", nameTh: "นครปฐม", nameEn: "Nakhon Pathom", region: "central" },
  { slug: "nakhon-phanom", nameTh: "นครพนม", nameEn: "Nakhon Phanom", region: "northeast" },
  { slug: "nakhon-ratchasima", nameTh: "นครราชสีมา", nameEn: "Nakhon Ratchasima", region: "northeast" },
  { slug: "nakhon-sawan", nameTh: "นครสวรรค์", nameEn: "Nakhon Sawan", region: "central" },
  { slug: "nakhon-si-thammarat", nameTh: "นครศรีธรรมราช", nameEn: "Nakhon Si Thammarat", region: "south" },
  { slug: "nan", nameTh: "น่าน", nameEn: "Nan", region: "north" },
  { slug: "narathiwat", nameTh: "นราธิวาส", nameEn: "Narathiwat", region: "south" },
  { slug: "nong-bua-lamphu", nameTh: "หนองบัวลำภู", nameEn: "Nong Bua Lamphu", region: "northeast" },
  { slug: "nong-khai", nameTh: "หนองคาย", nameEn: "Nong Khai", region: "northeast" },
  { slug: "nonthaburi", nameTh: "นนทบุรี", nameEn: "Nonthaburi", region: "central" },
  { slug: "pathum-thani", nameTh: "ปทุมธานี", nameEn: "Pathum Thani", region: "central" },
  { slug: "pattani", nameTh: "ปัตตานี", nameEn: "Pattani", region: "south" },
  { slug: "phang-nga", nameTh: "พังงา", nameEn: "Phang Nga", region: "south" },
  { slug: "phatthalung", nameTh: "พัทลุง", nameEn: "Phatthalung", region: "south" },
  { slug: "phayao", nameTh: "พะเยา", nameEn: "Phayao", region: "north" },
  { slug: "phetchabun", nameTh: "เพชรบูรณ์", nameEn: "Phetchabun", region: "north" },
  { slug: "phetchaburi", nameTh: "เพชรบุรี", nameEn: "Phetchaburi", region: "west" },
  { slug: "phichit", nameTh: "พิจิตร", nameEn: "Phichit", region: "north" },
  { slug: "phitsanulok", nameTh: "พิษณุโลก", nameEn: "Phitsanulok", region: "north" },
  { slug: "phra-nakhon-si-ayutthaya", nameTh: "พระนครศรีอยุธยา", nameEn: "Phra Nakhon Si Ayutthaya", region: "central" },
  { slug: "phrae", nameTh: "แพร่", nameEn: "Phrae", region: "north" },
  { slug: "phuket", nameTh: "ภูเก็ต", nameEn: "Phuket", region: "south" },
  { slug: "prachinburi", nameTh: "ปราจีนบุรี", nameEn: "Prachinburi", region: "east" },
  { slug: "prachuap-khiri-khan", nameTh: "ประจวบคีรีขันธ์", nameEn: "Prachuap Khiri Khan", region: "west" },
  { slug: "ranong", nameTh: "ระนอง", nameEn: "Ranong", region: "south" },
  { slug: "ratchaburi", nameTh: "ราชบุรี", nameEn: "Ratchaburi", region: "west" },
  { slug: "rayong", nameTh: "ระยอง", nameEn: "Rayong", region: "east" },
  { slug: "roi-et", nameTh: "ร้อยเอ็ด", nameEn: "Roi Et", region: "northeast" },
  { slug: "sa-kaeo", nameTh: "สระแก้ว", nameEn: "Sa Kaeo", region: "east" },
  { slug: "sakon-nakhon", nameTh: "สกลนคร", nameEn: "Sakon Nakhon", region: "northeast" },
  { slug: "samut-prakan", nameTh: "สมุทรปราการ", nameEn: "Samut Prakan", region: "central" },
  { slug: "samut-sakhon", nameTh: "สมุทรสาคร", nameEn: "Samut Sakhon", region: "central" },
  { slug: "samut-songkhram", nameTh: "สมุทรสงคราม", nameEn: "Samut Songkhram", region: "central" },
  { slug: "saraburi", nameTh: "สระบุรี", nameEn: "Saraburi", region: "central" },
  { slug: "satun", nameTh: "สตูล", nameEn: "Satun", region: "south" },
  { slug: "sing-buri", nameTh: "สิงห์บุรี", nameEn: "Sing Buri", region: "central" },
  { slug: "sisaket", nameTh: "ศรีสะเกษ", nameEn: "Sisaket", region: "northeast" },
  { slug: "songkhla", nameTh: "สงขลา", nameEn: "Songkhla", region: "south" },
  { slug: "sukhothai", nameTh: "สุโขทัย", nameEn: "Sukhothai", region: "north" },
  { slug: "suphan-buri", nameTh: "สุพรรณบุรี", nameEn: "Suphan Buri", region: "central" },
  { slug: "surat-thani", nameTh: "สุราษฎร์ธานี", nameEn: "Surat Thani", region: "south" },
  { slug: "surin", nameTh: "สุรินทร์", nameEn: "Surin", region: "northeast" },
  { slug: "tak", nameTh: "ตาก", nameEn: "Tak", region: "west" },
  { slug: "trang", nameTh: "ตรัง", nameEn: "Trang", region: "south" },
  { slug: "trat", nameTh: "ตราด", nameEn: "Trat", region: "east" },
  { slug: "ubon-ratchathani", nameTh: "อุบลราชธานี", nameEn: "Ubon Ratchathani", region: "northeast" },
  { slug: "udon-thani", nameTh: "อุดรธานี", nameEn: "Udon Thani", region: "northeast" },
  { slug: "uthai-thani", nameTh: "อุทัยธานี", nameEn: "Uthai Thani", region: "central" },
  { slug: "uttaradit", nameTh: "อุตรดิตถ์", nameEn: "Uttaradit", region: "north" },
  { slug: "yala", nameTh: "ยะลา", nameEn: "Yala", region: "south" },
  { slug: "yasothon", nameTh: "ยโสธร", nameEn: "Yasothon", region: "northeast" },
];

export function getProvinceBySlug(slug: string): ThaiProvince | undefined {
  return thaiProvinces.find(province => province.slug === slug);
}
