param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$BundleDir = (Join-Path $Root "04_deployment_bundle")
)

$ErrorActionPreference = "Stop"

function Copy-RequiredFile {
  param(
    [string]$RelativePath
  )

  $source = Join-Path $Root $RelativePath
  if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
    throw "Required file missing: $RelativePath"
  }

  $target = Join-Path $BundleDir $RelativePath
  $targetParent = Split-Path -Parent $target
  New-Item -ItemType Directory -Force -Path $targetParent | Out-Null
  Copy-Item -LiteralPath $source -Destination $target -Force
}

function Copy-RequiredDirectoryFiles {
  param(
    [string]$RelativeDirectory,
    [string[]]$Include = @("*"),
    [string[]]$Exclude = @()
  )

  $sourceDir = Join-Path $Root $RelativeDirectory
  if (-not (Test-Path -LiteralPath $sourceDir -PathType Container)) {
    throw "Required directory missing: $RelativeDirectory"
  }

  Get-ChildItem -LiteralPath $sourceDir -Recurse -File -Include $Include | ForEach-Object {
    if ($Exclude -contains $_.Name) {
      return
    }
    $relative = $_.FullName.Substring($Root.Length).TrimStart("\", "/")
    Copy-RequiredFile -RelativePath $relative
  }
}

$bundleManifestSource = Join-Path $Root ".ops\contracts\HANDOFF_BUNDLE_MANIFEST.json"
if (-not (Test-Path -LiteralPath $bundleManifestSource -PathType Leaf)) {
  throw "Required manifest missing: .ops/contracts/HANDOFF_BUNDLE_MANIFEST.json"
}

$bundleManifest = Get-Content -LiteralPath $bundleManifestSource -Raw | ConvertFrom-Json

$forbiddenPatterns = @(
  "\\node_modules\\",
  "\\dist\\",
  "\\.git\\",
  "\\artifacts\\",
  "\\secrets\\",
  "\\cache\\",
  "\\.cache\\",
  "\\__pycache__\\",
  "\\coverage\\",
  "\\tmp\\",
  "\\temp\\",
  "\.env$",
  "\.pem$",
  "\.key$",
  "\.p12$",
  "\.pfx$",
  "keystore"
)

if (Test-Path -LiteralPath $BundleDir) {
  Get-ChildItem -LiteralPath $BundleDir -Force | Remove-Item -Recurse -Force
} else {
  New-Item -ItemType Directory -Force -Path $BundleDir | Out-Null
}

foreach ($file in $bundleManifest.requiredFiles) {
  Copy-RequiredFile -RelativePath $file
}

foreach ($directorySpec in $bundleManifest.requiredDirectories) {
  $include = @($directorySpec.include)
  $exclude = @($directorySpec.exclude)
  Copy-RequiredDirectoryFiles -RelativeDirectory $directorySpec.path -Include $include -Exclude $exclude
}

$historicalBlueprint = Join-Path $BundleDir "governance\SIRINX_V15_ARCHITECTURE_BLUEPRINT.md"
if (Test-Path -LiteralPath $historicalBlueprint) {
  Remove-Item -LiteralPath $historicalBlueprint -Force
}

@"
# SIRINX Real-File Server Handoff Bundle

Status: Server-Ready Hold

This folder is generated by infra/scripts/build-handoff-bundle.ps1.
It contains real copies of the governance docs, migration docs, infrastructure scripts, compose templates, and knowledge-vault handoff files required for server-team review.

Required validation:

```bash
python infra/scripts/validate-agent-contracts.py
bash infra/scripts/ultimate-validator.sh
```

This bundle must not contain production secrets, node_modules, dist, caches, keystores, or unrelated CHOKMA/gambling artifacts.

Deployment remains blocked until server access details and explicit human approval are provided.
"@ | Set-Content -LiteralPath (Join-Path $BundleDir "README.md") -Encoding UTF8

$bundleFiles = Get-ChildItem -LiteralPath $BundleDir -Recurse -File |
  Sort-Object FullName

$forbiddenHits = @()
foreach ($file in $bundleFiles) {
  $relative = $file.FullName.Substring($BundleDir.Length).TrimStart("\", "/")
  foreach ($pattern in @($bundleManifest.bundleExcludes) + $forbiddenPatterns) {
    if ($relative -match $pattern) {
      if ($relative -ne ".env.example") {
        $forbiddenHits += $relative
      }
    }
  }
}

if ($forbiddenHits.Count -gt 0) {
  throw "Forbidden files in bundle: $($forbiddenHits -join ', ')"
}

$manifestEntries = @()
$checksumLines = @()
foreach ($file in $bundleFiles) {
  $relative = $file.FullName.Substring($BundleDir.Length).TrimStart("\", "/").Replace("\", "/")
  $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash
  $manifestEntries += [pscustomobject]@{
    path = $relative
    bytes = $file.Length
    sha256 = $hash
  }
  $checksumLines += "$hash  $relative"
}

$manifest = [pscustomobject]@{
  generatedAt = (Get-Date).ToUniversalTime().ToString("o")
  sourceRoot = $Root
  trackedFileCount = $manifestEntries.Count
  fileCount = ($manifestEntries.Count + 2)
  trackedTotalBytes = ($manifestEntries | Measure-Object -Property bytes -Sum).Sum
  files = $manifestEntries
}

($manifest | ConvertTo-Json -Depth 5) | Set-Content -LiteralPath (Join-Path $BundleDir "MANIFEST.json") -Encoding UTF8
$checksumLines | Set-Content -LiteralPath (Join-Path $BundleDir "CHECKSUMS.SHA256.txt") -Encoding UTF8

$manifestLines = @(
  "# SIRINX Handoff Manifest",
  "",
  "- Generated at: $($manifest.generatedAt)",
  "- Source root: $Root",
  "- Tracked file count: $($manifest.trackedFileCount)",
  "- Total bytes: $($manifest.trackedTotalBytes)",
  "",
  "## Included Files"
)

foreach ($entry in $manifestEntries) {
  $manifestLines += "- ``$($entry.path)`` ($($entry.bytes) bytes)"
}

$manifestLines | Set-Content -LiteralPath (Join-Path $BundleDir "MANIFEST.md") -Encoding UTF8

$finalFiles = Get-ChildItem -LiteralPath $BundleDir -Recurse -File
[pscustomobject]@{
  bundleDir = $BundleDir
  fileCount = $finalFiles.Count
  totalBytes = ($finalFiles | Measure-Object -Property Length -Sum).Sum
  manifest = Join-Path $BundleDir "MANIFEST.json"
  checksums = Join-Path $BundleDir "CHECKSUMS.SHA256.txt"
} | ConvertTo-Json -Depth 3
