/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with: docs/seo/generate-province-energy-data.mjs
 *
 * Province-level solar resource facts, each with the source it came from.
 *
 * The figures are climate normals for a point at the province centroid, not a
 * site survey and not a savings promise. System loss, tilt, shading and the real
 * load profile all move the outcome, and this file is not allowed to claim they
 * do not.
 *
 * Coverage: 77 of 77 provinces at generation time. Provinces without
 * a record simply render no solar section, rather than rendering a guess.
 */

export type ProvinceEnergyFact = {
  /** Province centroid used for the lookup, in decimal degrees. */
  lat: number;
  lon: number;
  /** Global horizontal irradiation, kWh/m2/day. */
  irradiationDaily: number;
  /** Specific yield, kWh per kWp per year. Free-standing, 0 degree tilt, 14% system loss. */
  specificYield: number;
  source: {
    name: string;
    url: string;
    database: string;
    yearRange: string;
    retrievedAt: string;
    coordinateSource: string;
  };
};

export const provinceEnergyData: Record<string, ProvinceEnergyFact> = {
  "amnat-charoen": {
    lat: 15.86,
    lon: 104.63,
    irradiationDaily: 5.06,
    specificYield: 1392.91,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอำนาจเจริญ (wikidata)\"",
    },
  },
  "ang-thong": {
    lat: 14.59,
    lon: 100.48,
    irradiationDaily: 5.08,
    specificYield: 1379.37,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอ่างทอง (wikidata)\"",
    },
  },
  "bangkok": {
    lat: 13.7525,
    lon: 100.49416667,
    irradiationDaily: 5.12,
    specificYield: 1401.4,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"กรุงเทพมหานคร (wikidata)\"",
    },
  },
  "bueng-kan": {
    lat: 18.367,
    lon: 103.655,
    irradiationDaily: 4.8,
    specificYield: 1304.42,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดบึงกาฬ (wikidata)\"",
    },
  },
  "buriram": {
    lat: 15,
    lon: 103.11,
    irradiationDaily: 5.12,
    specificYield: 1399.9,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดบุรีรัมย์ (wikidata)\"",
    },
  },
  "chachoengsao": {
    lat: 13.69,
    lon: 101.07,
    irradiationDaily: 4.97,
    specificYield: 1355.75,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดฉะเชิงเทรา (wikidata)\"",
    },
  },
  "chai-nat": {
    lat: 15.18,
    lon: 100.13,
    irradiationDaily: 5.11,
    specificYield: 1384.93,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดชัยนาท (wikidata)\"",
    },
  },
  "chaiyaphum": {
    lat: 15.8,
    lon: 102.04,
    irradiationDaily: 5.1,
    specificYield: 1399.38,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดชัยภูมิ (wikidata)\"",
    },
  },
  "chanthaburi": {
    lat: 12.61,
    lon: 102.11,
    irradiationDaily: 4.86,
    specificYield: 1339.23,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดจันทบุรี (wikidata)\"",
    },
  },
  "chiang-mai": {
    lat: 18.8,
    lon: 98.98,
    irradiationDaily: 4.84,
    specificYield: 1301.85,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดเชียงใหม่ (wikidata)\"",
    },
  },
  "chiang-rai": {
    lat: 19.91,
    lon: 99.83,
    irradiationDaily: 4.93,
    specificYield: 1341.8,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดเชียงราย (wikidata)\"",
    },
  },
  "chonburi": {
    lat: 13.4,
    lon: 101,
    irradiationDaily: 4.92,
    specificYield: 1353.79,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดชลบุรี (wikidata)\"",
    },
  },
  "chumphon": {
    lat: 10.493,
    lon: 99.179,
    irradiationDaily: 5.01,
    specificYield: 1394.5,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดชุมพร (wikidata)\"",
    },
  },
  "kalasin": {
    lat: 16.433,
    lon: 103.507,
    irradiationDaily: 5.1,
    specificYield: 1398.78,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดกาฬสินธุ์ (wikidata)\"",
    },
  },
  "kamphaeng-phet": {
    lat: 16.47,
    lon: 99.52,
    irradiationDaily: 4.93,
    specificYield: 1323.96,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดกำแพงเพชร (wikidata)\"",
    },
  },
  "kanchanaburi": {
    lat: 14.00416667,
    lon: 99.54916667,
    irradiationDaily: 5.02,
    specificYield: 1363.29,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดกาญจนบุรี (wikidata)\"",
    },
  },
  "khon-kaen": {
    lat: 16.42,
    lon: 102.83,
    irradiationDaily: 5.13,
    specificYield: 1400.26,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดขอนแก่น (wikidata)\"",
    },
  },
  "krabi": {
    lat: 8.058,
    lon: 98.917,
    irradiationDaily: 4.97,
    specificYield: 1361.3,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดกระบี่ (wikidata)\"",
    },
  },
  "lampang": {
    lat: 18.29,
    lon: 99.48,
    irradiationDaily: 4.83,
    specificYield: 1305.31,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดลำปาง (wikidata)\"",
    },
  },
  "lamphun": {
    lat: 18.5,
    lon: 99.08,
    irradiationDaily: 4.82,
    specificYield: 1313.06,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดลำพูน (wikidata)\"",
    },
  },
  "loei": {
    lat: 17.49,
    lon: 101.73,
    irradiationDaily: 4.88,
    specificYield: 1329.06,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดเลย (wikidata)\"",
    },
  },
  "lopburi": {
    lat: 14.8,
    lon: 100.62,
    irradiationDaily: 5.09,
    specificYield: 1388.82,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดลพบุรี (wikidata)\"",
    },
  },
  "mae-hong-son": {
    lat: 19.27,
    lon: 97.93,
    irradiationDaily: 4.87,
    specificYield: 1325.94,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดแม่ฮ่องสอน (wikidata)\"",
    },
  },
  "maha-sarakham": {
    lat: 16.18,
    lon: 103.29,
    irradiationDaily: 5.13,
    specificYield: 1407.81,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดมหาสารคาม (wikidata)\"",
    },
  },
  "mukdahan": {
    lat: 16.54,
    lon: 104.72,
    irradiationDaily: 4.99,
    specificYield: 1374.67,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดมุกดาหาร (wikidata)\"",
    },
  },
  "nakhon-nayok": {
    lat: 14.2,
    lon: 101.22,
    irradiationDaily: 4.91,
    specificYield: 1335.53,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครนายก (wikidata)\"",
    },
  },
  "nakhon-pathom": {
    lat: 13.82,
    lon: 100.06,
    irradiationDaily: 5.09,
    specificYield: 1384.13,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครปฐม (wikidata)\"",
    },
  },
  "nakhon-phanom": {
    lat: 17.4,
    lon: 104.78,
    irradiationDaily: 4.85,
    specificYield: 1327.05,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครพนม (wikidata)\"",
    },
  },
  "nakhon-ratchasima": {
    lat: 14.97,
    lon: 102.1,
    irradiationDaily: 5.07,
    specificYield: 1389.32,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครราชสีมา (wikidata)\"",
    },
  },
  "nakhon-sawan": {
    lat: 15.7,
    lon: 100.07,
    irradiationDaily: 5.1,
    specificYield: 1375.68,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครสวรรค์ (wikidata)\"",
    },
  },
  "nakhon-si-thammarat": {
    lat: 8.4,
    lon: 99.97,
    irradiationDaily: 5.03,
    specificYield: 1377.48,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนครศรีธรรมราช (wikidata)\"",
    },
  },
  "nan": {
    lat: 18.78,
    lon: 100.77,
    irradiationDaily: 4.78,
    specificYield: 1294.8,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดน่าน (wikidata)\"",
    },
  },
  "narathiwat": {
    lat: 6.43,
    lon: 101.82,
    irradiationDaily: 5.3,
    specificYield: 1454.53,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนราธิวาส (wikidata)\"",
    },
  },
  "nong-bua-lamphu": {
    lat: 17.2,
    lon: 102.44,
    irradiationDaily: 5.01,
    specificYield: 1367.22,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดหนองบัวลำภู (wikidata)\"",
    },
  },
  "nong-khai": {
    lat: 17.88,
    lon: 102.74,
    irradiationDaily: 4.99,
    specificYield: 1357.9,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดหนองคาย (wikidata)\"",
    },
  },
  "nonthaburi": {
    lat: 13.8,
    lon: 100.18,
    irradiationDaily: 5.09,
    specificYield: 1385.94,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดนนทบุรี (wikidata)\"",
    },
  },
  "pathum-thani": {
    lat: 14.02,
    lon: 100.52,
    irradiationDaily: 5.04,
    specificYield: 1371.14,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดปทุมธานี (wikidata)\"",
    },
  },
  "pattani": {
    lat: 6.87,
    lon: 101.24,
    irradiationDaily: 5.1,
    specificYield: 1400.1,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดปัตตานี (wikidata)\"",
    },
  },
  "phang-nga": {
    lat: 8.45,
    lon: 98.53,
    irradiationDaily: 4.94,
    specificYield: 1349.9,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพังงา (wikidata)\"",
    },
  },
  "phatthalung": {
    lat: 7.63,
    lon: 100.07,
    irradiationDaily: 5.18,
    specificYield: 1423.16,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพัทลุง (wikidata)\"",
    },
  },
  "phayao": {
    lat: 19.17,
    lon: 99.91,
    irradiationDaily: 4.9,
    specificYield: 1332.11,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพะเยา (wikidata)\"",
    },
  },
  "phetchabun": {
    lat: 16.42,
    lon: 101.16,
    irradiationDaily: 4.94,
    specificYield: 1336.33,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดเพชรบูรณ์ (wikidata)\"",
    },
  },
  "phetchaburi": {
    lat: 13.111,
    lon: 99.946,
    irradiationDaily: 5.15,
    specificYield: 1411.45,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดเพชรบุรี (wikidata)\"",
    },
  },
  "phichit": {
    lat: 16.44,
    lon: 100.35,
    irradiationDaily: 5.01,
    specificYield: 1348.25,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพิจิตร (wikidata)\"",
    },
  },
  "phitsanulok": {
    lat: 16.826,
    lon: 100.26,
    irradiationDaily: 4.97,
    specificYield: 1338.7,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพิษณุโลก (wikidata)\"",
    },
  },
  "phra-nakhon-si-ayutthaya": {
    lat: 14.36,
    lon: 100.57,
    irradiationDaily: 5.01,
    specificYield: 1361.65,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดพระนครศรีอยุธยา (wikidata)\"",
    },
  },
  "phrae": {
    lat: 18.15,
    lon: 100.16,
    irradiationDaily: 4.89,
    specificYield: 1327.42,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดแพร่ (wikidata)\"",
    },
  },
  "phuket": {
    lat: 7.88,
    lon: 98.38,
    irradiationDaily: 5.42,
    specificYield: 1510.98,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดภูเก็ต (wikidata)\"",
    },
  },
  "prachinburi": {
    lat: 14.05,
    lon: 101.38,
    irradiationDaily: 4.97,
    specificYield: 1352.15,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดปราจีนบุรี (wikidata)\"",
    },
  },
  "prachuap-khiri-khan": {
    lat: 11.82,
    lon: 99.8,
    irradiationDaily: 5.34,
    specificYield: 1485.47,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดประจวบคีรีขันธ์ (wikidata)\"",
    },
  },
  "ranong": {
    lat: 9.97,
    lon: 98.63,
    irradiationDaily: 5.03,
    specificYield: 1395.64,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดระนอง (wikidata)\"",
    },
  },
  "ratchaburi": {
    lat: 13.54,
    lon: 99.82,
    irradiationDaily: 5.06,
    specificYield: 1372.13,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดราชบุรี (wikidata)\"",
    },
  },
  "rayong": {
    lat: 12.68,
    lon: 101.28,
    irradiationDaily: 5.15,
    specificYield: 1412.69,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดระยอง (wikidata)\"",
    },
  },
  "roi-et": {
    lat: 16.05,
    lon: 103.65,
    irradiationDaily: 5.11,
    specificYield: 1404.03,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดร้อยเอ็ด (wikidata)\"",
    },
  },
  "sa-kaeo": {
    lat: 13.82,
    lon: 102.07,
    irradiationDaily: 5.1,
    specificYield: 1397.28,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสระแก้ว (wikidata)\"",
    },
  },
  "sakon-nakhon": {
    lat: 17.17,
    lon: 104.15,
    irradiationDaily: 5,
    specificYield: 1372.97,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสกลนคร (wikidata)\"",
    },
  },
  "samut-prakan": {
    lat: 13.61,
    lon: 100.61,
    irradiationDaily: 5.14,
    specificYield: 1407.56,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสมุทรปราการ (wikidata)\"",
    },
  },
  "samut-sakhon": {
    lat: 13.54,
    lon: 100.28,
    irradiationDaily: 5.19,
    specificYield: 1422.74,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสมุทรสาคร (wikidata)\"",
    },
  },
  "samut-songkhram": {
    lat: 13.413,
    lon: 100.002,
    irradiationDaily: 5.22,
    specificYield: 1413.86,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสมุทรสงคราม (wikidata)\"",
    },
  },
  "saraburi": {
    lat: 14.53,
    lon: 100.88,
    irradiationDaily: 4.97,
    specificYield: 1352.12,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสระบุรี (wikidata)\"",
    },
  },
  "satun": {
    lat: 6.62,
    lon: 100.07,
    irradiationDaily: 5.16,
    specificYield: 1416.3,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสตูล (wikidata)\"",
    },
  },
  "sing-buri": {
    lat: 14.89,
    lon: 100.4,
    irradiationDaily: 5.11,
    specificYield: 1389.64,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสิงห์บุรี (wikidata)\"",
    },
  },
  "sisaket": {
    lat: 15.12,
    lon: 104.322,
    irradiationDaily: 5.12,
    specificYield: 1401.23,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดศรีสะเกษ (wikidata)\"",
    },
  },
  "songkhla": {
    lat: 7.21,
    lon: 100.56,
    irradiationDaily: 5.24,
    specificYield: 1433.8,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสงขลา (wikidata)\"",
    },
  },
  "sukhothai": {
    lat: 17.01,
    lon: 99.75,
    irradiationDaily: 4.99,
    specificYield: 1346.2,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสุโขทัย (wikidata)\"",
    },
  },
  "suphan-buri": {
    lat: 14.474,
    lon: 100.118,
    irradiationDaily: 5.08,
    specificYield: 1377.12,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสุพรรณบุรี (wikidata)\"",
    },
  },
  "surat-thani": {
    lat: 9.14,
    lon: 99.33,
    irradiationDaily: 5.11,
    specificYield: 1397.04,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสุราษฎร์ธานี (wikidata)\"",
    },
  },
  "surin": {
    lat: 14.88,
    lon: 103.49,
    irradiationDaily: 5.11,
    specificYield: 1400.93,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดสุรินทร์ (wikidata)\"",
    },
  },
  "tak": {
    lat: 16.884,
    lon: 99.125,
    irradiationDaily: 4.8,
    specificYield: 1296.14,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดตาก (wikidata)\"",
    },
  },
  "trang": {
    lat: 7.56,
    lon: 99.61,
    irradiationDaily: 4.85,
    specificYield: 1326.82,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดตรัง (wikidata)\"",
    },
  },
  "trat": {
    lat: 12.23,
    lon: 102.5,
    irradiationDaily: 4.69,
    specificYield: 1286.82,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดตราด (wikidata)\"",
    },
  },
  "ubon-ratchathani": {
    lat: 15.229,
    lon: 104.851,
    irradiationDaily: 5.09,
    specificYield: 1392.21,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอุบลราชธานี (wikidata)\"",
    },
  },
  "udon-thani": {
    lat: 17.41,
    lon: 102.79,
    irradiationDaily: 5.01,
    specificYield: 1366.46,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอุดรธานี (wikidata)\"",
    },
  },
  "uthai-thani": {
    lat: 15.38,
    lon: 100.03,
    irradiationDaily: 5.11,
    specificYield: 1382.79,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอุทัยธานี (wikidata)\"",
    },
  },
  "uttaradit": {
    lat: 17.63,
    lon: 100.1,
    irradiationDaily: 4.96,
    specificYield: 1337.3,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดอุตรดิตถ์ (wikidata)\"",
    },
  },
  "yala": {
    lat: 6.55,
    lon: 101.29,
    irradiationDaily: 5.22,
    specificYield: 1418.2,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดยะลา (wikidata)\"",
    },
  },
  "yasothon": {
    lat: 15.79,
    lon: 104.15,
    irradiationDaily: 5.1,
    specificYield: 1400.07,
    source: {
      name: "PVGIS v5.3, European Commission Joint Research Centre",
      url: "https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html",
      database: "PVGIS-ERA5",
      yearRange: "2005-2023",
      retrievedAt: "2026-09-26",
      coordinateSource: "th.wikipedia.org article \"จังหวัดยโสธร (wikidata)\"",
    },
  },
};

export function getProvinceEnergyFact(slug: string): ProvinceEnergyFact | null {
  return provinceEnergyData[slug] ?? null;
}

export const provinceEnergyCoverage = {
  withData: Object.keys(provinceEnergyData).length,
  total: 77,
};
